#!/usr/bin/env bash

versions="$(ls versions)"

declare -A arr

latest_release=$(curl -s https://piston-meta.mojang.com/mc/game/version_manifest_v2.json \
    | jq -r '.latest.release')

for i in $versions; do
    last_version=$(grep "^last_minecraft_version" versions/"$i"/gradle.properties \
        | cut -d = -f 2)
    if [[ -z "$last_version" ]]; then
        last_version="$latest_release"
    fi

    IFS="." read -r i_major i_minor i_patch <<<"$i"
    IFS="." read -r last_major last_minor last_patch <<<"$last_version"

    if [[ -z "$i_patch" ]]; then
        i_patch=0
    fi
    if [[ -z "$last_patch" ]]; then
        last_patch=0
    fi

    START_PATCH="$i_patch"
    END_PATCH="$last_patch"

    arr["$i"]=$(
    seq "$START_PATCH" "$END_PATCH" \
        | awk -v mm="$i_major.$i_minor" '{print mm ($1==0 ? "" : "." $1)}' \
        | jq -R . | jq -s -c .
    )
done


jq -n --argjson n "${#arr[@]}" '
    reduce range($n) as $i ({};
            .[$ARGS.positional[$i]] = [$ARGS.positional[$i+$n]]
    )
' --args "${!arr[@]}" "${arr[@]}" > versions.json

echo "${!arr[@]}" | jq -c -r -R 'split(" ")'

